/**
 * Check runner: runs every check in this repo, records pass/fail, duration and
 * the error output of anything that failed, then rewrites TESTS.md.
 *
 * There is no test framework here on purpose — each check is a standalone
 * script that exits non-zero on failure, so the runner is a loop over
 * spawnSync. Adding Jest or Vitest would be more configuration than test code.
 *
 * Run: node scripts/run-checks.mjs
 * Exit code is the number of failing checks, so CI can gate on it.
 */

import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const CHECKS = [
  {
    name: "scrub-check",
    cmd: ["bash", ["scripts/scrub-check.sh"]],
    guards: "No personal or institutional identifier in any tracked file. This is the publish gate.",
  },
  {
    name: "turns-log",
    cmd: ["npx", ["tsx", "src/memory/turns.selfcheck.ts"]],
    guards: "Per-turn log round-trips every column. Drift here silently destroys the improvement curve.",
  },
  {
    name: "success-cache",
    cmd: ["npx", ["tsx", "src/memory/successCache.selfcheck.ts"]],
    guards: "The bypass answers with no model, so nothing downstream can catch a wrong match. Asserts the misses: reversed word order, an added restriction, a flipped negation, any date-bearing argument, a write tool, a different tool schema. Plus that the offline summarizer ranks and dedupes.",
  },
  {
    name: "mistake-memory",
    cmd: ["npx", ["tsx", "scripts/test_mistakes.ts"]],
    guards: "Failed tool calls are captured and recalled — the mechanism the project is built on.",
  },
  {
    name: "mistake-memory-stress",
    cmd: ["npx", ["tsx", "scripts/stress_mistakes.ts"]],
    guards: "Attacks the headline sentence itself: that EVERY failure is replayed into EVERY later turn. Covers single unfixed failures, cross-session fixes, id-varying errors, prefix collisions, concurrency and restart.",
  },
  {
    name: "config-guards",
    cmd: ["npx", ["tsx", "scripts/test_config_guards.ts"]],
    guards: "Unconfigured mailbox and catalogue tools refuse before reaching the network.",
  },
  {
    name: "prompt-enrichment",
    cmd: ["npx", ["tsx", "scripts/demo_prompt_enrichment.ts"]],
    guards: "A recorded lesson reaches the next turn's system prompt. This is the README's headline claim, so it fails the build rather than quietly flattening.",
  },
  {
    name: "typecheck",
    cmd: ["npx", ["tsc", "--noEmit"]],
    guards: "Whole tree typechecks.",
    // Known, pre-existing, documented in CODEBASE.md. Counted and reported
    // rather than hidden, but they do not fail the run.
    knownBad: ["telegram.ts", "council.ts", "osVision.ts"],
  },
];

/** Runs one check. Returns its result including trimmed output. */
function run({ name, cmd: [bin, args], guards, knownBad }) {
  const started = Date.now();
  const r = spawnSync(bin, args, { encoding: "utf8", shell: process.platform === "win32" });
  const ms = Date.now() - started;
  const output = `${r.stdout ?? ""}${r.stderr ?? ""}`.trim();

  let pass = r.status === 0;
  let note = "";

  if (knownBad) {
    // Count error lines, split into known-bad files vs everything else.
    const errs = output.split("\n").filter((l) => /error TS\d+/.test(l));
    const unexpected = errs.filter((l) => !knownBad.some((f) => l.includes(f)));
    pass = unexpected.length === 0;
    note = `${errs.length} pre-existing error${errs.length === 1 ? "" : "s"} in ${knownBad.join(", ")}`;
    if (unexpected.length) note += `; ${unexpected.length} NEW`;
    return { name, guards, pass, ms, exit: r.status, output, note, errs, unexpected };
  }

  return { name, guards, pass, ms, exit: r.status, output, note };
}

const results = CHECKS.map(run);
const failed = results.filter((r) => !r.pass);
const totalMs = results.reduce((a, r) => a + r.ms, 0);
const rate = ((results.length - failed.length) / results.length) * 100;

const row = (r) =>
  `| ${r.name} | ${r.pass ? "pass" : "**FAIL**"} | ${r.ms} | ${r.exit} | ${r.note || "—"} |`;

const md = `# TESTS — 01-helm-agent-runtime

Generated by \`node scripts/run-checks.mjs\`. Do not edit by hand; rerun it.

Last run: ${new Date().toISOString().slice(0, 19).replace("T", " ")} UTC

## Summary

| | |
|---|---|
| Checks | ${results.length} |
| Passed | ${results.length - failed.length} |
| Failed | ${failed.length} |
| Pass rate | ${rate.toFixed(0)}% |
| Wall time | ${(totalMs / 1000).toFixed(1)} s |

Every number on this page is produced by the runner on a real run. Nothing here
is estimated.

## Cases

| Check | Result | ms | exit | Notes |
|---|---|---|---|---|
${results.map(row).join("\n")}

## What each check guards

${results.map((r) => `**${r.name}** — ${r.guards}`).join("\n\n")}

## Failures

${
  failed.length === 0
    ? "_None on this run._"
    : failed
        .map(
          (r) =>
            `### ${r.name} (exit ${r.exit})\n\n\`\`\`\n${r.output.split("\n").slice(-25).join("\n")}\n\`\`\``,
        )
        .join("\n\n")
}

## Known errors, tolerated

Errors that a check reports but which do not fail the run. They are listed in
full so that a new one cannot hide among them — the runner compares against the
file list, so an error in any other file turns the run red.

${
  results
    .filter((r) => r.errs?.length)
    .map(
      (r) =>
        `### ${r.name}\n\n\`\`\`\n${r.errs.join("\n")}\n\`\`\`\n\nInherited from the imported codebase and listed in \`CODEBASE.md\`. Not introduced by work in this repo.`,
    )
    .join("\n\n") || "_None._"
}

## What is NOT covered

These are the honest gaps, not an oversight list to be quietly dropped:

- **No end-to-end agent-loop test.** A real turn costs a live model call. The one
  measured turn in the log was run by hand.
- **Mailbox and catalogue tools are only tested in their refusal path.** The
  success path needs live credentials and a network, so it is unexercised here.
- **MCP server startup is untested.** No \`mcp_servers.json\` exists in this tree.
- **Coverage is not measured.** With five checks the number would be misleading.
`;

writeFileSync("TESTS.md", md);

for (const r of results) {
  console.log(`${r.pass ? "pass" : "FAIL"}  ${r.name.padEnd(16)} ${String(r.ms).padStart(6)} ms  ${r.note}`);
}
console.log(`\n${results.length - failed.length}/${results.length} passed in ${(totalMs / 1000).toFixed(1)}s — wrote TESTS.md`);
process.exit(failed.length);
